
require("prototypes/item-groups/item-groups")

require("mods/5dim")
require("mods/aai-industry")
require("mods/angels-storage-containers")
require("mods/atomic-overhaul")
require("mods/base")
require("mods/bzmods")
require("mods/flare-stack")
require("mods/krastorio")
require("mods/modules")
require("mods/se-space-trains")
require("mods/smr")
require("mods/space-exploration")
require("mods/spidertron-tiers")
require("mods/ultimate-belts")