--Armor
data.raw.armor["light-armor"].subgroup = "armor-armor"
data.raw.armor["light-armor"].order = "a"
data.raw.armor["heavy-armor"].subgroup = "armor-armor"
data.raw.armor["heavy-armor"].order = "b"
data.raw.armor["modular-armor"].subgroup = "armor-armor"
data.raw.armor["modular-armor"].order = "c"
-- data.raw.armor["power-armor"].subgroup = "armor-power-armor"
-- data.raw.armor["power-armor"].order = "a"
-- data.raw.armor["power-armor-mk2"].subgroup = "armor-power-armor"
-- data.raw.armor["power-armor-mk2"].order = "aa"
data.raw.item["solar-panel-equipment"].subgroup = "armor-solar"
data.raw.item["solar-panel-equipment"].order = "a"
-- data.raw.item["fusion-reactor-equipment"].subgroup = "armor-reactor"
-- data.raw.item["fusion-reactor-equipment"].order = "a"
-- data.raw.item["battery-equipment"].subgroup = "armor-baterry"
-- data.raw.item["battery-equipment"].order = "a"
-- data.raw.item["battery-mk2-equipment"].subgroup = "armor-baterry"
-- data.raw.item["battery-mk2-equipment"].order = "a"
data.raw.item["exoskeleton-equipment"].subgroup = "armor-exoesqueleto"
data.raw.item["exoskeleton-equipment"].order = "a"
-- data.raw.item["personal-roboport-equipment"].subgroup = "armor-roboport"
-- data.raw.item["personal-roboport-equipment"].order = "a"
-- data.raw.item["personal-roboport-mk2-equipment"].subgroup = "armor-roboport"
-- data.raw.item["personal-roboport-mk2-equipment"].order = "aa"
-- data.raw.item["energy-shield-equipment"].subgroup = "armor-shield"
-- data.raw.item["energy-shield-equipment"].order = "a"
-- data.raw.item["energy-shield-mk2-equipment"].subgroup = "armor-shield"
-- data.raw.item["energy-shield-mk2-equipment"].order = "aa"
data.raw.item["personal-laser-defense-equipment"].subgroup = "armor-laser"
data.raw.item["personal-laser-defense-equipment"].order = "a"
data.raw.item["night-vision-equipment"].subgroup = "armor-util"
data.raw.item["night-vision-equipment"].order = "d"
data.raw.item["belt-immunity-equipment"].subgroup = "armor-util"
data.raw.item["belt-immunity-equipment"].order = "a"
data.raw.item["discharge-defense-equipment"].subgroup = "armor-util"
data.raw.item["discharge-defense-equipment"].order = "b"
data.raw.capsule["discharge-defense-remote"].subgroup = "armor-util"
data.raw.capsule["discharge-defense-remote"].order = "c"

if mods["jetpack"] then
    data.raw.item["jetpack-1"].subgroup = "armor-jetpack"
    data.raw.item["jetpack-1"].order = "a"
    data.raw.item["jetpack-2"].subgroup = "armor-jetpack"
    data.raw.item["jetpack-2"].order = "b"
    data.raw.item["jetpack-3"].subgroup = "armor-jetpack"
    data.raw.item["jetpack-3"].order = "c"
    data.raw.item["jetpack-4"].subgroup = "armor-jetpack"
    data.raw.item["jetpack-4"].order = "d"
end

if mods["space-exploration"] then
    data.raw.item["se-lifesupport-equipment-1"].subgroup = "armor-lifesupport"
    data.raw.item["se-lifesupport-equipment-1"].order = "a"
    data.raw.item["se-lifesupport-equipment-2"].subgroup = "armor-lifesupport"
    data.raw.item["se-lifesupport-equipment-2"].order = "b"
    data.raw.item["se-lifesupport-equipment-3"].subgroup = "armor-lifesupport"
    data.raw.item["se-lifesupport-equipment-3"].order = "c"
    data.raw.item["se-lifesupport-equipment-4"].subgroup = "armor-lifesupport"
    data.raw.item["se-lifesupport-equipment-4"].order = "d"
end