data.raw.item["burner-inserter"].subgroup = "transport-inserter-vanilla"
data.raw.item["burner-inserter"].order = "a"
data.raw.item["long-handed-inserter"].subgroup = "transport-inserter-vanilla"
data.raw.item["long-handed-inserter"].order = "b"
data.raw.item["inserter"].subgroup = "transport-inserter"
data.raw.item["inserter"].order = "a"
data.raw.item["fast-inserter"].subgroup = "transport-inserter"
data.raw.item["fast-inserter"].order = "aa"
data.raw.item["filter-inserter"].subgroup = "transport-filter-inserter"
data.raw.item["filter-inserter"].order = "a"
data.raw.item["stack-inserter"].subgroup = "transport-stack-inserter"
data.raw.item["stack-inserter"].order = "a"
data.raw.item["stack-filter-inserter"].subgroup = "transport-stack-filter-inserter"
data.raw.item["stack-filter-inserter"].order = "a"
data.raw.item["assembling-machine-1"].subgroup = "assembling-machine"
data.raw.item["assembling-machine-1"].order = "a"
data.raw.item["assembling-machine-2"].subgroup = "assembling-machine"
data.raw.item["assembling-machine-2"].order = "b"
data.raw.item["assembling-machine-3"].subgroup = "assembling-machine"
data.raw.item["assembling-machine-3"].order = "c"

-- Furnaces
data.raw.item["electric-furnace"].subgroup = "furnace-electric"
data.raw.item["electric-furnace"].order = "a"

-- Misc early and specialty mining drills and such
data.raw.item["stone-furnace"].subgroup = "mining-misc"
data.raw.item["stone-furnace"].order = "b"
data.raw.item["steel-furnace"].subgroup = "mining-misc"
data.raw.item["steel-furnace"].order = "c"
data.raw.item["5d-industrial-furnace"].subgroup = "mining-misc"
data.raw.item["5d-industrial-furnace"].order = "e"
data.raw.item["area-mining-drill"].subgroup = "mining-misc"
data.raw.item["area-mining-drill"].order = "e"

-- Misc and specialty labs
data.raw.item["burner-lab"].subgroup = "lab-specialty"
data.raw.item["burner-lab"].order = "a"
data.raw.item["biusart-lab"].subgroup = "lab-specialty"
data.raw.item["biusart-lab"].order = "b"
data.raw.item["se-space-science-lab"].subgroup = "lab-specialty"
data.raw.item["se-space-science-lab"].order = "c"
data.raw.item["kr-singularity-lab"].subgroup = "lab-specialty"
data.raw.item["kr-singularity-lab"].order = "d"