
-- Weapons Equipment
data.raw.gun["flamethrower"].subgroup = "equipment-flame"
data.raw.gun["flamethrower"].order = "a"
data.raw.item["land-mine"].subgroup = "equipment-capsule"
data.raw.item["land-mine"].order = "ac"
data.raw.gun["rocket-launcher"].subgroup = "equipment-rocket"
data.raw.gun["rocket-launcher"].order = "a"
data.raw.gun["shotgun"].subgroup = "equipment-shotgun"
data.raw.gun["shotgun"].order = "a"
data.raw.gun["combat-shotgun"].subgroup = "equipment-shotgun"
data.raw.gun["combat-shotgun"].order = "b"
data.raw.gun["submachine-gun"].subgroup = "equipment-bullet"
data.raw.gun["submachine-gun"].order = "b"
data.raw.gun["pistol"].subgroup = "equipment-bullet"
data.raw.gun["pistol"].order = "a"
data.raw.ammo["piercing-rounds-magazine"].subgroup = "equipment-bullet"
data.raw.ammo["piercing-rounds-magazine"].order = "d"
data.raw.ammo["firearm-magazine"].subgroup = "equipment-bullet"
data.raw.ammo["firearm-magazine"].order = "c"
data.raw.ammo["flamethrower-ammo"].subgroup = "equipment-flame"
data.raw.ammo["flamethrower-ammo"].order = "b"
data.raw.ammo["explosive-rocket"].subgroup = "equipment-rocket"
data.raw.ammo["explosive-rocket"].order = "c"
data.raw.ammo["rocket"].subgroup = "equipment-rocket"
data.raw.ammo["rocket"].order = "b"
data.raw.ammo["piercing-shotgun-shell"].subgroup = "equipment-shotgun"
data.raw.ammo["piercing-shotgun-shell"].order = "d"
data.raw.ammo["shotgun-shell"].subgroup = "equipment-shotgun"
data.raw.ammo["shotgun-shell"].order = "c"
data.raw.capsule["grenade"].subgroup = "equipment-capsule"
data.raw.capsule["grenade"].order = "a"
data.raw.capsule["cluster-grenade"].subgroup = "equipment-capsule"
data.raw.capsule["cluster-grenade"].order = "ab"
data.raw.capsule["poison-capsule"].subgroup = "equipment-capsule"
data.raw.capsule["poison-capsule"].order = "b"
data.raw.capsule["slowdown-capsule"].subgroup = "equipment-capsule"
data.raw.capsule["slowdown-capsule"].order = "c"
data.raw.capsule["defender-capsule"].subgroup = "equipment-capsule"
data.raw.capsule["defender-capsule"].order = "d"
data.raw.capsule["distractor-capsule"].subgroup = "equipment-capsule"
data.raw.capsule["distractor-capsule"].order = "e"
data.raw.capsule["destroyer-capsule"].subgroup = "equipment-capsule"
data.raw.capsule["destroyer-capsule"].order = "f"
data.raw.ammo["uranium-rounds-magazine"].subgroup = "equipment-bullet"
data.raw.ammo["uranium-rounds-magazine"].order = "e"
-- data.raw.gun["railgun"].subgroup = "equipment-railgun"
-- data.raw.gun["railgun"].order = "a"
-- data.raw.ammo["railgun-dart"].subgroup = "equipment-railgun"
-- data.raw.ammo["railgun-dart"].order = "b"
data.raw.ammo["atomic-bomb"].subgroup = "equipment-rocket"
data.raw.ammo["atomic-bomb"].order = "d"

if mods["space-exploration"] then
    data.raw.item["se-meteor-point-defence"].subgroup = "equipment-space-defense"
    data.raw.item["se-meteor-point-defence"].order = "a"
    data.raw.item["se-meteor-defence"].subgroup = "equipment-space-defense"
    data.raw.item["se-meteor-defence"].order = "b"
    data.raw.item["se-delivery-cannon-weapon"].subgroup = "equipment-space-defense"
    data.raw.item["se-delivery-cannon-weapon"].order = "c"

    data.raw.ammo["se-meteor-point-defence-ammo"].subgroup = "equipment-space-ammo"
    data.raw.ammo["se-meteor-point-defence-ammo"].order = "a"
    data.raw.ammo["se-meteor-defence-ammo"].subgroup = "equipment-space-ammo"
    data.raw.ammo["se-meteor-defence-ammo"].order = "b"
    data.raw.item["se-delivery-cannon-weapon-capsule"].subgroup = "equipment-space-ammo"
    data.raw.item["se-delivery-cannon-weapon-capsule"].order = "c"
end