--Intermediate
-- data.raw.item["iron-stick"].subgroup = "intermediate-misc"
-- data.raw.item["iron-stick"].order = "a"
-- data.raw.item["empty-barrel"].subgroup = "intermediate-misc"
-- data.raw.item["empty-barrel"].order = "h"
-- data.raw.recipe["empty-barrel"].subgroup = "intermediate-misc"
-- data.raw.recipe["empty-barrel"].order = "h"
-- data.raw.item["engine-unit"].subgroup = "intermediate-misc"
-- data.raw.item["engine-unit"].order = "b"
-- data.raw.item["electric-engine-unit"].subgroup = "intermediate-misc"
-- data.raw.item["electric-engine-unit"].order = "c"
-- data.raw.item["explosives"].subgroup = "intermediate-misc"
-- data.raw.item["explosives"].order = "f"
-- data.raw.item["battery"].subgroup = "intermediate-misc"
-- data.raw.item["battery"].order = "e"
-- data.raw.item["flying-robot-frame"].subgroup = "intermediate-misc"
-- data.raw.item["flying-robot-frame"].order = "d"
-- data.raw.tool["automation-science-pack"].subgroup = "intermediate-lab"
-- data.raw.tool["logistic-science-pack"].subgroup = "intermediate-lab"
-- data.raw.tool["chemical-science-pack"].subgroup = "intermediate-lab"
-- data.raw.tool["military-science-pack"].subgroup = "intermediate-lab"
-- data.raw.tool["production-science-pack"].subgroup = "intermediate-lab"
-- data.raw.tool["utility-science-pack"].subgroup = "intermediate-lab"
-- data.raw.tool["space-science-pack"].subgroup = "intermediate-lab"
-- data.raw.item["electronic-circuit"].subgroup = "intermediate-chip"
-- data.raw.item["electronic-circuit"].order = "a"
-- data.raw.item["advanced-circuit"].subgroup = "intermediate-chip"
-- data.raw.item["advanced-circuit"].order = "b"
-- data.raw.item["processing-unit"].subgroup = "intermediate-chip"
-- data.raw.item["processing-unit"].order = "c"
-- data.raw.item["copper-cable"].subgroup = "intermediate-gear"
-- data.raw.item["copper-cable"].order = "a"
-- data.raw.item["iron-gear-wheel"].subgroup = "intermediate-gear"
-- data.raw.item["iron-gear-wheel"].order = "b"


data.raw.item["low-density-structure"].subgroup = "intermediate-silo"
data.raw.item["low-density-structure"].order = "b"
data.raw.item["rocket-fuel"].subgroup = "intermediate-silo"
data.raw.item["rocket-fuel"].order = "c"
data.raw.item["rocket-control-unit"].subgroup = "intermediate-silo"
data.raw.item["rocket-control-unit"].order = "d"
data.raw.item["rocket-part"].subgroup = "intermediate-silo"
data.raw.item["rocket-part"].order = "e"

data.raw.item["rocket-silo"].subgroup = "intermediate-rocket"
data.raw.item["rocket-silo"].order = "a"

data.raw.item["satellite"].subgroup = "intermediate-satellite"
data.raw.item["satellite"].order = "a"

if mods["space-exploration"] then
    data.raw.item["se-space-probe-rocket-silo"].subgroup = "intermediate-rocket"
    data.raw.item["se-space-probe-rocket-silo"].order = "b"
    data.raw.item["se-rocket-launch-pad"].subgroup = "intermediate-rocket"
    data.raw.item["se-rocket-launch-pad"].order = "c"
    data.raw.item["se-rocket-landing-pad"].subgroup = "intermediate-rocket"
    data.raw.item["se-rocket-landing-pad"].order = "d"
    data.raw.item["se-space-elevator"].subgroup = "intermediate-rocket"
    data.raw.item["se-space-elevator"].order = "e"
    data.raw.item["se-delivery-cannon"].subgroup = "intermediate-rocket"
    data.raw.item["se-delivery-cannon"].order = "f"
    data.raw.item["se-delivery-cannon-chest"].subgroup = "intermediate-rocket"
    data.raw.item["se-delivery-cannon-chest"].order = "g"

    data.raw.item["se-space-capsule"].subgroup = "intermediate-rocket-parts"
    data.raw.item["se-space-capsule"].order = "a"
    data.raw.item["se-space-capsule-scorched"].subgroup = "intermediate-rocket-parts"
    data.raw.item["se-space-capsule-scorched"].order = "b"
    data.raw.item["se-cargo-rocket-section"].subgroup = "intermediate-rocket-parts"
    data.raw.item["se-cargo-rocket-section"].order = "c"
    data.raw.item["se-cargo-rocket-section-packed"].subgroup = "intermediate-rocket-parts"
    data.raw.item["se-cargo-rocket-section-packed"].order = "d"
    data.raw.item["se-cargo-rocket-cargo-pod"].subgroup = "intermediate-rocket-parts"
    data.raw.item["se-cargo-rocket-cargo-pod"].order = "e"
    data.raw.item["se-cargo-rocket-fuel-tank"].subgroup = "intermediate-rocket-parts"
    data.raw.item["se-cargo-rocket-fuel-tank"].order = "f"
    data.raw.item["se-delivery-cannon-capsule"].subgroup = "intermediate-rocket-parts"
    data.raw.item["se-delivery-cannon-capsule"].order = "a"

    data.raw.item["se-space-probe-rocket"].subgroup = "intermediate-satellite"
    data.raw.item["se-space-probe-rocket"].order = "b"
    data.raw.item["se-arcosphere-collector"].subgroup = "intermediate-satellite"
    data.raw.item["se-arcosphere-collector"].order = "c"
end