--Liquids
data.raw.item["chemical-plant"].subgroup = "liquid-plant"
data.raw.item["chemical-plant"].order = "a"
data.raw.item["oil-refinery"].subgroup = "liquid-refinery"
data.raw.item["oil-refinery"].order = "a"
data.raw.item["pumpjack"].subgroup = "liquid-pump"
data.raw.item["pumpjack"].order = "a"
data.raw.item["offshore-pump"].subgroup = "liquid-offshore-pump"
data.raw.item["offshore-pump"].order = "a"
data.raw.item["pump"].subgroup = "liquid-small-pump"
data.raw.item["pump"].order = "a"
data.raw.item["storage-tank"].subgroup = "liquid-store"
data.raw.item["storage-tank"].order = "a"

-- Pipes
data.raw.item["pipe"].subgroup = "transport-pipe"
data.raw.item["pipe"].order = "a"
data.raw.item["pipe-to-ground"].subgroup = "transport-pipe"
data.raw.item["pipe-to-ground"].order = "b"
data.raw.item["5d-pipe-to-ground-mk1-30"].subgroup = "transport-pipe"
data.raw.item["5d-pipe-to-ground-mk1-30"].order = "c"
data.raw.item["5d-pipe-to-ground-mk1-50"].subgroup = "transport-pipe"
data.raw.item["5d-pipe-to-ground-mk1-50"].order = "d"
data.raw.item["kr-steel-pipe"].subgroup = "transport-pipe"
data.raw.item["kr-steel-pipe"].order = "e"
data.raw.item["kr-steel-pipe-to-ground"].subgroup = "transport-pipe"
data.raw.item["kr-steel-pipe-to-ground"].order = "f"

data.raw.item["se-space-pipe"].subgroup = "transport-pipe-ground"
data.raw.item["se-space-pipe"].order = "a"
data.raw.item["se-space-pipe-to-ground"].subgroup = "transport-pipe-ground"
data.raw.item["se-space-pipe-to-ground"].order = "b"
-- data.raw.item["se-space-pipe-long-7"].subgroup = "transport-pipe-ground"
-- data.raw.item["se-space-pipe-long-7"].order = "c"
-- data.raw.item["se-space-pipe-long-straight"].subgroup = "transport-pipe-ground"
-- data.raw.item["se-space-pipe-long-straight"].order = "d"
-- data.raw.item["se-space-pipe-long-junction"].subgroup = "transport-pipe-ground"
-- data.raw.item["se-space-pipe-long-junction"].order = "e"

-- Fluid Must Flow item group defines
data.raw.item["duct-small"].subgroup = "transport-pipe-jumbo"
data.raw.item["duct-small"].order = "a"
data.raw.item["duct"].subgroup = "transport-pipe-jumbo"
data.raw.item["duct"].order = "b"
data.raw.item["duct-long"].subgroup = "transport-pipe-jumbo"
data.raw.item["duct-long"].order = "c"
data.raw.item["duct-t-junction"].subgroup = "transport-pipe-jumbo"
data.raw.item["duct-t-junction"].order = "d"
data.raw.item["duct-curve"].subgroup = "transport-pipe-jumbo"
data.raw.item["duct-curve"].order = "e"
data.raw.item["duct-cross"].subgroup = "transport-pipe-jumbo"
data.raw.item["duct-cross"].order = "f"
data.raw.item["duct-underground"].subgroup = "transport-pipe-jumbo"
data.raw.item["duct-underground"].order = "g"
data.raw.item["non-return-duct"].subgroup = "transport-pipe-jumbo"
data.raw.item["non-return-duct"].order = "h"
data.raw.item["duct-end-point-intake"].subgroup = "transport-pipe-jumbo"
data.raw.item["duct-end-point-intake"].order = "i"
data.raw.item["duct-end-point-outtake"].subgroup = "transport-pipe-jumbo"
data.raw.item["duct-end-point-outtake"].order = "j"

-- Angels & Krastorio large/pressure tanks


-- Recipes
-- data.raw.recipe["sulfuric-acid"].subgroup = "liquid-recipe"
-- data.raw.recipe["basic-oil-processing"].subgroup = "liquid-recipe"
-- data.raw.recipe["advanced-oil-processing"].subgroup = "liquid-recipe"
-- data.raw.recipe["heavy-oil-cracking"].subgroup = "liquid-recipe"
-- data.raw.recipe["light-oil-cracking"].subgroup = "liquid-recipe"
-- data.raw.recipe["sulfuric-acid"].subgroup = "liquid-recipe"
-- data.raw.recipe["solid-fuel-from-light-oil"].subgroup = "liquid-recipe"
-- data.raw.recipe["solid-fuel-from-petroleum-gas"].subgroup = "liquid-recipe"
-- data.raw.recipe["solid-fuel-from-heavy-oil"].subgroup = "liquid-recipe"
-- data.raw.recipe["lubricant"].subgroup = "liquid-recipe"
-- data.raw.recipe["coal-liquefaction"].subgroup = "liquid-recipe"