data.raw.item["kr-small-roboport"].subgroup = "logistic-roboport-specialty"
data.raw.item["kr-small-roboport"].order = "a"
data.raw.item["kr-large-roboport"].subgroup = "logistic-roboport-specialty"
data.raw.item["kr-large-roboport"].order = "b"


--Logistic
data.raw.item["logistic-robot"].subgroup = "logistic-robot"
data.raw.item["logistic-robot"].order = "a"
data.raw.item["construction-robot"].subgroup = "logistic-robot-c"
data.raw.item["construction-robot"].order = "a"
data.raw.item["roboport"].subgroup = "logistic-roboport"
data.raw.item["roboport"].order = "a"
data.raw.item["logistic-chest-passive-provider"].subgroup = "logistic-pasive"
data.raw.item["logistic-chest-passive-provider"].order = "a"
data.raw.item["logistic-chest-buffer"].subgroup = "logistic-buffer"
data.raw.item["logistic-chest-buffer"].order = "a"
data.raw.item["logistic-chest-active-provider"].subgroup = "logistic-active"
data.raw.item["logistic-chest-active-provider"].order = "a"
data.raw.item["logistic-chest-storage"].subgroup = "logistic-storage"
data.raw.item["logistic-chest-storage"].order = "a"
data.raw.item["logistic-chest-requester"].subgroup = "logistic-requester"
data.raw.item["logistic-chest-requester"].order = "a"
data.raw.item["red-wire"].subgroup = "logistic-wire"
data.raw.item["red-wire"].order = "b"
data.raw.item["green-wire"].subgroup = "logistic-wire"
data.raw.item["green-wire"].order = "c"
data.raw.item["beacon"].subgroup = "beacon"
data.raw.item["beacon"].order = "a"
data.raw.item["arithmetic-combinator"].subgroup = "logistic-comb"
data.raw.item["arithmetic-combinator"].order = "a"
data.raw.item["decider-combinator"].subgroup = "logistic-comb"
data.raw.item["decider-combinator"].order = "b"
data.raw.item["constant-combinator"].subgroup = "logistic-comb"
data.raw.item["constant-combinator"].order = "c"
-- data.raw["deconstruction-item"]["deconstruction-planner"].subgroup = "logistic-plan"
-- data.raw["deconstruction-item"]["deconstruction-planner"].order = "c"
-- data.raw["blueprint"]["blueprint"].subgroup = "logistic-plan"
-- data.raw["blueprint"]["blueprint"].order = "b"
-- data.raw["blueprint-book"]["blueprint-book"].subgroup = "logistic-plan"
-- data.raw["blueprint-book"]["blueprint-book"].order = "a"
data.raw.item["power-switch"].subgroup = "logistic-comb"
data.raw.item["power-switch"].order = "d"
data.raw.item["programmable-speaker"].subgroup = "logistic-comb"
data.raw.item["programmable-speaker"].order = "d"

if mods["aai-signal-transmission"] then
    data.raw.item["aai-signal-sender"].subgroup = "logistic-util"
    data.raw.item["aai-signal-sender"].order = "a"
    data.raw.item["aai-signal-receiver"].subgroup = "logistic-util"
    data.raw.item["aai-signal-receiver"].order = "b"
end

if mods["stack-combinator"] then
  data.raw.item["stack-combinator"].subgroup = "logistic-comb-custom"
  data.raw.item["stack-combinator"].order = "a"
end

if mods["crafting_combinator"] then
  data.raw.item["crafting_combinator:crafting-combinator"].subgroup = "logistic-comb-custom"
  data.raw.item["crafting_combinator:crafting-combinator"].order = "b"
  data.raw.item["crafting_combinator:recipe-combinator"].subgroup = "logistic-comb-custom"
  data.raw.item["crafting_combinator:recipe-combinator"].order = "c"
end

if mods["compaktcircuit"] then
    data.raw["item-with-tags"]["compaktcircuit-processor_with_tags"].subgroup = "logistic-comb-custom"
    data.raw["item-with-tags"]["compaktcircuit-processor_with_tags"].order = "d"
  data.raw.item["compaktcircuit-processor"].subgroup = "logistic-comb-custom"
  data.raw.item["compaktcircuit-processor"].order = "e"
--   data.raw["item-with-tags"]["compaktcircuit-processor_with_tags_1x1"].subgroup = "logistic-comb-custom"
--     data.raw["item-with-tags"]["compaktcircuit-processor_with_tags_1x1"].order = "f"
  data.raw.item["compaktcircuit-processor_1x1"].subgroup = "logistic-comb-custom"
  data.raw.item["compaktcircuit-processor_1x1"].order = "g"
end

if mods["nixie-tubes"] then
  data.raw.item["nixie-tube"].subgroup = "logistic-nixie"
  data.raw.item["nixie-tube"].order = "a"
  data.raw.item["nixie-tube-alpha"].subgroup = "logistic-nixie"
  data.raw.item["nixie-tube-alpha"].order = "b"
  data.raw.item["nixie-tube-small"].subgroup = "logistic-nixie"
  data.raw.item["nixie-tube-small"].order = "c"
end

if mods["angelsaddons-storage"] then
    data.raw.item["silo"].subgroup = "store-solid"
    data.raw.item["silo"].order = "i"
    data.raw.item["silo-active-provider"].subgroup = "logistic-active"
    data.raw.item["silo-active-provider"].order = "g"
    data.raw.item["silo-passive-provider"].subgroup = "logistic-pasive"
    data.raw.item["silo-passive-provider"].order = "g"
    data.raw.item["silo-requester"].subgroup = "logistic-requester"
    data.raw.item["silo-requester"].order = "g"
    data.raw.item["silo-storage"].subgroup = "logistic-storage"
    data.raw.item["silo-storage"].order = "g"
    data.raw.item["silo-buffer"].subgroup = "logistic-buffer"
    data.raw.item["silo-buffer"].order = "g"

    data.raw.item["angels-warehouse"].subgroup = "store-solid"
    data.raw.item["angels-warehouse"].order = "j"
    data.raw.item["angels-warehouse-active-provider"].subgroup = "logistic-active"
    data.raw.item["angels-warehouse-active-provider"].order = "h"
    data.raw.item["angels-warehouse-passive-provider"].subgroup = "logistic-pasive"
    data.raw.item["angels-warehouse-passive-provider"].order = "h"
    data.raw.item["angels-warehouse-requester"].subgroup = "logistic-requester"
    data.raw.item["angels-warehouse-requester"].order = "h"
    data.raw.item["angels-warehouse-storage"].subgroup = "logistic-storage"
    data.raw.item["angels-warehouse-storage"].order = "h"
    data.raw.item["angels-warehouse-buffer"].subgroup = "logistic-buffer"
    data.raw.item["angels-warehouse-buffer"].order = "h"

    data.raw.recipe["angels-warehouse"].subgroup = "store-solid"
    data.raw.recipe["angels-warehouse"].order = "j"
    data.raw.recipe["angels-warehouse-active-provider"].subgroup = "logistic-active"
    data.raw.recipe["angels-warehouse-active-provider"].order = "h"
    data.raw.recipe["angels-warehouse-passive-provider"].subgroup = "logistic-pasive"
    data.raw.recipe["angels-warehouse-passive-provider"].order = "h"
    data.raw.recipe["angels-warehouse-requester"].subgroup = "logistic-requester"
    data.raw.recipe["angels-warehouse-requester"].order = "h"
    data.raw.recipe["angels-warehouse-storage"].subgroup = "logistic-storage"
    data.raw.recipe["angels-warehouse-storage"].order = "h"
    data.raw.recipe["angels-warehouse-buffer"].subgroup = "logistic-buffer"
    data.raw.recipe["angels-warehouse-buffer"].order = "h"

    -- if data.raw.item["silo"].name ~= nil then
    --     data.raw.item["silo-ore1"].subgroup = "store-solid-angels"
    --     data.raw.item["silo-ore1"].order = "a"
    --     data.raw.item["silo-ore2"].subgroup = "store-solid-angels"
    --     data.raw.item["silo-ore2"].order = "b"
    --     data.raw.item["silo-ore3"].subgroup = "store-solid-angels"
    --     data.raw.item["silo-ore3"].order = "c"
    --     data.raw.item["silo-ore4"].subgroup = "store-solid-angels"
    --     data.raw.item["silo-ore4"].order = "d"
    --     data.raw.item["silo-ore5"].subgroup = "store-solid-angels"
    --     data.raw.item["silo-ore5"].order = "e"
    --     data.raw.item["silo-ore6"].subgroup = "store-solid-angels"
    --     data.raw.item["silo-ore6"].order = "f"
    --     data.raw.item["silo-coal"].subgroup = "store-solid-angels"
    --     data.raw.item["silo-coal"].order = "g"
    -- end
end