
--Transport
data.raw.item["loader"].subgroup = "transport-loader"
data.raw.item["loader"].order = "a"
data.raw.item["fast-loader"].subgroup = "transport-loader"
data.raw.item["fast-loader"].order = "b"
data.raw.item["express-loader"].subgroup = "transport-loader"
data.raw.item["express-loader"].order = "c"
data.raw.item["splitter"].subgroup = "transport-splitters"
data.raw.item["splitter"].order = "a"
data.raw.item["fast-splitter"].subgroup = "transport-splitters"
data.raw.item["fast-splitter"].order = "b"
data.raw.item["express-splitter"].subgroup = "transport-splitters"
data.raw.item["express-splitter"].order = "c"
data.raw.item["underground-belt"].subgroup = "transport-ground"
data.raw.item["underground-belt"].order = "a"
data.raw.item["fast-underground-belt"].subgroup = "transport-ground"
data.raw.item["fast-underground-belt"].order = "b"
data.raw.item["express-underground-belt"].subgroup = "transport-ground"
data.raw.item["express-underground-belt"].order = "c"
-- data.raw.item["transport-belt"].subgroup = "transport-belt-vanilla"
-- data.raw.item["transport-belt"].order = "a"
-- data.raw.item["fast-transport-belt"].subgroup = "transport-belt-vanilla"
-- data.raw.item["fast-transport-belt"].order = "b"
-- data.raw.item["express-transport-belt"].subgroup = "transport-belt-vanilla"
-- data.raw.item["express-transport-belt"].order = "c"

if mods["Krastorio2"] then
  data.raw.item["kr-advanced-transport-belt"].subgroup = "transport-belt-vanilla"
  data.raw.item["kr-advanced-transport-belt"].order = "d"
  data.raw.item["kr-superior-transport-belt"].subgroup = "transport-belt-vanilla"
  data.raw.item["kr-superior-transport-belt"].order = "e"

  data.raw.item["kr-advanced-underground-belt"].subgroup = "transport-ground-vanilla"
  data.raw.item["kr-advanced-underground-belt"].order = "d"
  data.raw.item["kr-superior-underground-belt"].subgroup = "transport-ground-vanilla"
  data.raw.item["kr-superior-underground-belt"].order = "e"

  data.raw.item["kr-advanced-splitter"].subgroup = "transport-splitters-vanilla"
  data.raw.item["kr-advanced-splitter"].order = "d"
  data.raw.item["kr-superior-splitter"].subgroup = "transport-splitters-vanilla"
  data.raw.item["kr-superior-splitter"].order = "e"
end

if mods["space-exploration"] then
  data.raw.item["se-space-transport-belt"].subgroup = "transport-space-belt-vanilla"
  data.raw.item["se-space-transport-belt"].order = "a"
  data.raw.item["se-deep-space-transport-belt-black"].subgroup = "transport-space-belt-vanilla"
  data.raw.item["se-deep-space-transport-belt-black"].order = "b"
  data.raw.item["se-deep-space-transport-belt-white"].subgroup = "transport-space-belt-vanilla"
  data.raw.item["se-deep-space-transport-belt-white"].order = "c"
  data.raw.item["se-deep-space-transport-belt-red"].subgroup = "transport-space-belt-vanilla"
  data.raw.item["se-deep-space-transport-belt-red"].order = "d"
  data.raw.item["se-deep-space-transport-belt-magenta"].subgroup = "transport-space-belt-vanilla"
  data.raw.item["se-deep-space-transport-belt-magenta"].order = "e"
  data.raw.item["se-deep-space-transport-belt-blue"].subgroup = "transport-space-belt-vanilla"
  data.raw.item["se-deep-space-transport-belt-blue"].order = "f"
  data.raw.item["se-deep-space-transport-belt-cyan"].subgroup = "transport-space-belt-vanilla"
  data.raw.item["se-deep-space-transport-belt-cyan"].order = "g"
  data.raw.item["se-deep-space-transport-belt-green"].subgroup = "transport-space-belt-vanilla"
  data.raw.item["se-deep-space-transport-belt-green"].order = "h"
  data.raw.item["se-deep-space-transport-belt-yellow"].subgroup = "transport-space-belt-vanilla"
  data.raw.item["se-deep-space-transport-belt-yellow"].order = "i"


  data.raw.item["se-space-splitter"].subgroup = "transport-space-splitter-vanilla"
  data.raw.item["se-space-splitter"].order = "a"
  data.raw.item["se-deep-space-splitter-black"].subgroup = "transport-space-splitter-vanilla"
  data.raw.item["se-deep-space-splitter-black"].order = "b"
  data.raw.item["se-deep-space-splitter-white"].subgroup = "transport-space-splitter-vanilla"
  data.raw.item["se-deep-space-splitter-white"].order = "c"
  data.raw.item["se-deep-space-splitter-red"].subgroup = "transport-space-splitter-vanilla"
  data.raw.item["se-deep-space-splitter-red"].order = "d"
  data.raw.item["se-deep-space-splitter-magenta"].subgroup = "transport-space-splitter-vanilla"
  data.raw.item["se-deep-space-splitter-magenta"].order = "e"
  data.raw.item["se-deep-space-splitter-blue"].subgroup = "transport-space-splitter-vanilla"
  data.raw.item["se-deep-space-splitter-blue"].order = "f"
  data.raw.item["se-deep-space-splitter-cyan"].subgroup = "transport-space-splitter-vanilla"
  data.raw.item["se-deep-space-splitter-cyan"].order = "g"
  data.raw.item["se-deep-space-splitter-green"].subgroup = "transport-space-splitter-vanilla"
  data.raw.item["se-deep-space-splitter-green"].order = "h"
  data.raw.item["se-deep-space-splitter-yellow"].subgroup = "transport-space-splitter-vanilla"
  data.raw.item["se-deep-space-splitter-yellow"].order = "i"


  data.raw.item["se-space-underground-belt"].subgroup = "transport-space-underground-vanilla"
  data.raw.item["se-space-underground-belt"].order = "a"
  data.raw.item["se-deep-space-underground-belt-black"].subgroup = "transport-space-underground-vanilla"
  data.raw.item["se-deep-space-underground-belt-black"].order = "b"
  data.raw.item["se-deep-space-underground-belt-white"].subgroup = "transport-space-underground-vanilla"
  data.raw.item["se-deep-space-underground-belt-white"].order = "c"
  data.raw.item["se-deep-space-underground-belt-red"].subgroup = "transport-space-underground-vanilla"
  data.raw.item["se-deep-space-underground-belt-red"].order = "d"
  data.raw.item["se-deep-space-underground-belt-magenta"].subgroup = "transport-space-underground-vanilla"
  data.raw.item["se-deep-space-underground-belt-magenta"].order = "e"
  data.raw.item["se-deep-space-underground-belt-blue"].subgroup = "transport-space-underground-vanilla"
  data.raw.item["se-deep-space-underground-belt-blue"].order = "f"
  data.raw.item["se-deep-space-underground-belt-cyan"].subgroup = "transport-space-underground-vanilla"
  data.raw.item["se-deep-space-underground-belt-cyan"].order = "g"
  data.raw.item["se-deep-space-underground-belt-green"].subgroup = "transport-space-underground-vanilla"
  data.raw.item["se-deep-space-underground-belt-green"].order = "h"
  data.raw.item["se-deep-space-underground-belt-yellow"].subgroup = "transport-space-underground-vanilla"
  data.raw.item["se-deep-space-underground-belt-yellow"].order = "i"
end

if mods["UltimateBelts"] then
  data.raw.item["ultra-fast-belt"].subgroup = "transport-ultimate-belt"
  data.raw.item["ultra-fast-belt"].order = "a"
  data.raw.item["extreme-fast-belt"].subgroup = "transport-ultimate-belt"
  data.raw.item["extreme-fast-belt"].order = "b"
  data.raw.item["ultra-express-belt"].subgroup = "transport-ultimate-belt"
  data.raw.item["ultra-express-belt"].order = "c"
  data.raw.item["extreme-express-belt"].subgroup = "transport-ultimate-belt"
  data.raw.item["extreme-express-belt"].order = "d"
  data.raw.item["ultimate-belt"].subgroup = "transport-ultimate-belt"
  data.raw.item["ultimate-belt"].order = "e"

  data.raw.item["ultra-fast-underground-belt"].subgroup = "transport-ultimate-underground"
  data.raw.item["ultra-fast-underground-belt"].order = "a"
  data.raw.item["extreme-fast-underground-belt"].subgroup = "transport-ultimate-underground"
  data.raw.item["extreme-fast-underground-belt"].order = "b"
  data.raw.item["ultra-express-underground-belt"].subgroup = "transport-ultimate-underground"
  data.raw.item["ultra-express-underground-belt"].order = "c"
  data.raw.item["extreme-express-underground-belt"].subgroup = "transport-ultimate-underground"
  data.raw.item["extreme-express-underground-belt"].order = "d"
  data.raw.item["original-ultimate-underground-belt"].subgroup = "transport-ultimate-underground"
  data.raw.item["original-ultimate-underground-belt"].order = "e"

  data.raw.item["ultra-fast-splitter"].subgroup = "transport-ultimate-splitter"
  data.raw.item["ultra-fast-splitter"].order = "a"
  data.raw.item["extreme-fast-splitter"].subgroup = "transport-ultimate-splitter"
  data.raw.item["extreme-fast-splitter"].order = "b"
  data.raw.item["ultra-express-splitter"].subgroup = "transport-ultimate-splitter"
  data.raw.item["ultra-express-splitter"].order = "c"
  data.raw.item["extreme-express-splitter"].subgroup = "transport-ultimate-splitter"
  data.raw.item["extreme-express-splitter"].order = "d"
  data.raw.item["original-ultimate-splitter"].subgroup = "transport-ultimate-splitter"
  data.raw.item["original-ultimate-splitter"].order = "e"

  data.raw.item["ub-ultra-fast-miniloader"].subgroup = "transport-ultimate-miniloader"
  data.raw.item["ub-ultra-fast-miniloader"].order = "a"
  data.raw.item["ub-extreme-fast-miniloader"].subgroup = "transport-ultimate-miniloader"
  data.raw.item["ub-extreme-fast-miniloader"].order = "c"
  data.raw.item["ub-ultra-express-miniloader"].subgroup = "transport-ultimate-miniloader"
  data.raw.item["ub-ultra-express-miniloader"].order = "e"
  data.raw.item["ub-extreme-express-miniloader"].subgroup = "transport-ultimate-miniloader"
  data.raw.item["ub-extreme-express-miniloader"].order = "g"
  data.raw.item["ub-ultimate-miniloader"].subgroup = "transport-ultimate-miniloader"
  data.raw.item["ub-ultimate-miniloader"].order = "h"


  data.raw.item["ub-ultra-fast-filter-miniloader"].subgroup = "transport-ultimate-filter-miniloader"
  data.raw.item["ub-ultra-fast-filter-miniloader"].order = "b"
  data.raw.item["ub-extreme-fast-filter-miniloader"].subgroup = "transport-ultimate-filter-miniloader"
  data.raw.item["ub-extreme-fast-filter-miniloader"].order = "d"
  data.raw.item["ub-ultra-express-filter-miniloader"].subgroup = "transport-ultimate-filter-miniloader"
  data.raw.item["ub-ultra-express-filter-miniloader"].order = "f"
  data.raw.item["ub-extreme-express-filter-miniloader"].subgroup = "transport-ultimate-filter-miniloader"
  data.raw.item["ub-extreme-express-filter-miniloader"].order = "g"
  data.raw.item["ub-ultimate-filter-miniloader"].subgroup = "transport-ultimate-filter-miniloader"
  data.raw.item["ub-ultimate-filter-miniloader"].order = "i"
end



-- data.raw.item["pipe"].subgroup = "transport-pipe"
-- data.raw.item["pipe"].order = "a"
-- data.raw.item["pipe-to-ground"].subgroup = "transport-pipe-ground"
-- data.raw.item["pipe-to-ground"].order = "a"
-- data.raw.item["wooden-chest"].subgroup = "store-solid"
-- data.raw.item["wooden-chest"].order = "a"
-- data.raw.item["iron-chest"].subgroup = "store-solid"
-- data.raw.item["iron-chest"].order = "b"
-- data.raw.item["steel-chest"].subgroup = "store-solid"
-- data.raw.item["steel-chest"].order = "c"