
-- Miniloaders
-- data.raw.item["miniloader"].subgroup = "transport-miniloader-vanilla"
-- data.raw.item["miniloader"].order = "a"
-- data.raw.item["filter-miniloader"].subgroup = "transport-miniloader-vanilla"
-- data.raw.item["filter-miniloader"].order = "b"
-- data.raw.item["fast-miniloader"].subgroup = "transport-miniloader-vanilla"
-- data.raw.item["fast-miniloader"].order = "c"
-- data.raw.item["fast-filter-miniloader"].subgroup = "transport-miniloader-vanilla"
-- data.raw.item["fast-filter-miniloader"].order = "d"
-- data.raw.item["express-miniloader"].subgroup = "transport-miniloader-vanilla"
-- data.raw.item["express-miniloader"].order = "e"
-- data.raw.item["express-filter-miniloader"].subgroup = "transport-miniloader-vanilla"
-- data.raw.item["express-filter-miniloader"].order = "f"
-- data.raw.item["kr-advanced-miniloader"].subgroup = "transport-miniloader-vanilla"
-- data.raw.item["kr-advanced-miniloader"].order = "g"
-- data.raw.item["kr-advanced-filter-miniloader"].subgroup = "transport-miniloader-vanilla"
-- data.raw.item["kr-advanced-filter-miniloader"].order = "h"
-- data.raw.item["kr-superior-miniloader"].subgroup = "transport-miniloader-vanilla"
-- data.raw.item["kr-superior-miniloader"].order = "i"
-- data.raw.item["kr-superior-filter-miniloader"].subgroup = "transport-miniloader-vanilla"
-- data.raw.item["kr-superior-filter-miniloader"].order = "j"


-- Convenient space loader grouping with SE and KR combined
data.raw.item["space-miniloader"].subgroup = "transport-se-miniloader"
data.raw.item["space-miniloader"].order = "a"
data.raw.item["space-filter-miniloader"].subgroup = "transport-se-miniloader"
data.raw.item["space-filter-miniloader"].order = "b"
data.raw.item["deep-space-miniloader"].subgroup = "transport-se-miniloader"
data.raw.item["deep-space-miniloader"].order = "c"
data.raw.item["deep-space-filter-miniloader"].subgroup = "transport-se-miniloader"
data.raw.item["deep-space-filter-miniloader"].order = "d"
data.raw.item["kr-se-loader"].subgroup = "transport-se-miniloader"
data.raw.item["kr-se-loader"].order = "e"
data.raw.recipe["kr-se-loader"].subgroup = "transport-se-miniloader"
data.raw.recipe["kr-se-loader"].order = "e"
data.raw.item["kr-se-deep-space-loader-black"].subgroup = "transport-se-miniloader"
data.raw.item["kr-se-deep-space-loader-black"].order = "f"
data.raw.recipe["kr-se-deep-space-loader-black"].subgroup = "transport-se-miniloader"
data.raw.recipe["kr-se-deep-space-loader-black"].order = "f"


data.raw.item["kr-loader"].subgroup = "transport-kr-miniloader"
data.raw.item["kr-loader"].order = "a"
data.raw.item["kr-fast-loader"].subgroup = "transport-kr-miniloader"
data.raw.item["kr-fast-loader"].order = "b"
data.raw.item["kr-express-loader"].subgroup = "transport-kr-miniloader"
data.raw.item["kr-express-loader"].order = "c"
data.raw.item["kr-advanced-loader"].subgroup = "transport-kr-miniloader"
data.raw.item["kr-advanced-loader"].order = "e"
data.raw.item["kr-superior-loader"].subgroup = "transport-kr-miniloader"
data.raw.item["kr-superior-loader"].order = "f"

-- data.raw.item["5d-01-miniloader"].subgroup = "transport-miniloader"
-- data.raw.item["5d-01-miniloader"].order = "a"
-- data.raw.item["5d-02-miniloader"].subgroup = "transport-miniloader"
-- data.raw.item["5d-02-miniloader"].order = "b"
-- data.raw.item["5d-03-miniloader"].subgroup = "transport-miniloader"
-- data.raw.item["5d-03-miniloader"].order = "c"
data.raw.item["miniloader"].subgroup = "transport-miniloader"
data.raw.item["miniloader"].order = "a"
data.raw.item["fast-miniloader"].subgroup = "transport-miniloader"
data.raw.item["fast-miniloader"].order = "b"
data.raw.item["express-miniloader"].subgroup = "transport-miniloader"
data.raw.item["express-miniloader"].order = "c"
data.raw.item["5d-04-miniloader"].subgroup = "transport-miniloader"
data.raw.item["5d-04-miniloader"].order = "d"
data.raw.item["5d-05-miniloader"].subgroup = "transport-miniloader"
data.raw.item["5d-05-miniloader"].order = "e"
data.raw.item["5d-06-miniloader"].subgroup = "transport-miniloader"
data.raw.item["5d-06-miniloader"].order = "f"
data.raw.item["5d-07-miniloader"].subgroup = "transport-miniloader"
data.raw.item["5d-07-miniloader"].order = "g"
data.raw.item["5d-08-miniloader"].subgroup = "transport-miniloader"
data.raw.item["5d-08-miniloader"].order = "h"
data.raw.item["5d-09-miniloader"].subgroup = "transport-miniloader"
data.raw.item["5d-09-miniloader"].order = "i"
data.raw.item["5d-10-miniloader"].subgroup = "transport-miniloader"
data.raw.item["5d-10-miniloader"].order = "j"

-- data.raw.item["5d-01-filter-miniloader"].subgroup = "transport-filter-miniloader"
-- data.raw.item["5d-01-filter-miniloader"].order = "a"
-- data.raw.item["5d-02-filter-miniloader"].subgroup = "transport-filter-miniloader"
-- data.raw.item["5d-02-filter-miniloader"].order = "b"
-- data.raw.item["5d-03-filter-miniloader"].subgroup = "transport-filter-miniloader"
-- data.raw.item["5d-03-filter-miniloader"].order = "c"
data.raw.item["filter-miniloader"].subgroup = "transport-filter-miniloader"
data.raw.item["filter-miniloader"].order = "a"
data.raw.item["fast-filter-miniloader"].subgroup = "transport-filter-miniloader"
data.raw.item["fast-filter-miniloader"].order = "b"
data.raw.item["express-filter-miniloader"].subgroup = "transport-filter-miniloader"
data.raw.item["express-filter-miniloader"].order = "c"
data.raw.item["5d-04-filter-miniloader"].subgroup = "transport-filter-miniloader"
data.raw.item["5d-04-filter-miniloader"].order = "d"
data.raw.item["5d-05-filter-miniloader"].subgroup = "transport-filter-miniloader"
data.raw.item["5d-05-filter-miniloader"].order = "e"
data.raw.item["5d-06-filter-miniloader"].subgroup = "transport-filter-miniloader"
data.raw.item["5d-06-filter-miniloader"].order = "f"
data.raw.item["5d-07-filter-miniloader"].subgroup = "transport-filter-miniloader"
data.raw.item["5d-07-filter-miniloader"].order = "g"
data.raw.item["5d-08-filter-miniloader"].subgroup = "transport-filter-miniloader"
data.raw.item["5d-08-filter-miniloader"].order = "h"
data.raw.item["5d-09-filter-miniloader"].subgroup = "transport-filter-miniloader"
data.raw.item["5d-09-filter-miniloader"].order = "i"
data.raw.item["5d-10-filter-miniloader"].subgroup = "transport-filter-miniloader"
data.raw.item["5d-10-filter-miniloader"].order = "j"

